/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package taotaole.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class zz_yundb extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"zz_yundb\",\"namespace\":\"taotaole.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"int\"},{\"name\":\"order_id\",\"type\":\"int\"},{\"name\":\"mid\",\"type\":\"int\"},{\"name\":\"username\",\"type\":\"string\"},{\"name\":\"buy_id\",\"type\":\"int\"},{\"name\":\"goods_name\",\"type\":\"string\"},{\"name\":\"goods_price\",\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":8,\"scale\":2},{\"name\":\"price\",\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":8,\"scale\":2},{\"name\":\"qty\",\"type\":\"int\"},{\"name\":\"total\",\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":8,\"scale\":2},{\"name\":\"cover\",\"type\":\"int\"},{\"name\":\"qishu\",\"type\":\"int\"},{\"name\":\"yun_code\",\"type\":\"string\"},{\"name\":\"luck_code\",\"type\":\"string\"},{\"name\":\"db_time\",\"type\":\"string\"},{\"name\":\"timenum\",\"type\":\"string\"},{\"name\":\"status\",\"type\":\"int\"},{\"name\":\"ip\",\"type\":\"string\"},{\"name\":\"is_show\",\"type\":\"int\"},{\"name\":\"is_award\",\"type\":\"int\"},{\"name\":\"add_time\",\"type\":\"int\"},{\"name\":\"type\",\"type\":\"int\"},{\"name\":\"sharecode\",\"type\":\"string\"},{\"name\":\"fdis\",\"type\":\"int\"},{\"name\":\"agents\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public int id;
  @Deprecated public int order_id;
  @Deprecated public int mid;
  @Deprecated public java.lang.CharSequence username;
  @Deprecated public int buy_id;
  @Deprecated public java.lang.CharSequence goods_name;
  @Deprecated public java.nio.ByteBuffer goods_price;
  @Deprecated public java.nio.ByteBuffer price;
  @Deprecated public int qty;
  @Deprecated public java.nio.ByteBuffer total;
  @Deprecated public int cover;
  @Deprecated public int qishu;
  @Deprecated public java.lang.CharSequence yun_code;
  @Deprecated public java.lang.CharSequence luck_code;
  @Deprecated public java.lang.CharSequence db_time;
  @Deprecated public java.lang.CharSequence timenum;
  @Deprecated public int status;
  @Deprecated public java.lang.CharSequence ip;
  @Deprecated public int is_show;
  @Deprecated public int is_award;
  @Deprecated public int add_time;
  @Deprecated public int type;
  @Deprecated public java.lang.CharSequence sharecode;
  @Deprecated public int fdis;
  @Deprecated public java.lang.CharSequence agents;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public zz_yundb() {}

  /**
   * All-args constructor.
   */
  public zz_yundb(java.lang.Integer id, java.lang.Integer order_id, java.lang.Integer mid, java.lang.CharSequence username, java.lang.Integer buy_id, java.lang.CharSequence goods_name, java.nio.ByteBuffer goods_price, java.nio.ByteBuffer price, java.lang.Integer qty, java.nio.ByteBuffer total, java.lang.Integer cover, java.lang.Integer qishu, java.lang.CharSequence yun_code, java.lang.CharSequence luck_code, java.lang.CharSequence db_time, java.lang.CharSequence timenum, java.lang.Integer status, java.lang.CharSequence ip, java.lang.Integer is_show, java.lang.Integer is_award, java.lang.Integer add_time, java.lang.Integer type, java.lang.CharSequence sharecode, java.lang.Integer fdis, java.lang.CharSequence agents) {
    this.id = id;
    this.order_id = order_id;
    this.mid = mid;
    this.username = username;
    this.buy_id = buy_id;
    this.goods_name = goods_name;
    this.goods_price = goods_price;
    this.price = price;
    this.qty = qty;
    this.total = total;
    this.cover = cover;
    this.qishu = qishu;
    this.yun_code = yun_code;
    this.luck_code = luck_code;
    this.db_time = db_time;
    this.timenum = timenum;
    this.status = status;
    this.ip = ip;
    this.is_show = is_show;
    this.is_award = is_award;
    this.add_time = add_time;
    this.type = type;
    this.sharecode = sharecode;
    this.fdis = fdis;
    this.agents = agents;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return order_id;
    case 2: return mid;
    case 3: return username;
    case 4: return buy_id;
    case 5: return goods_name;
    case 6: return goods_price;
    case 7: return price;
    case 8: return qty;
    case 9: return total;
    case 10: return cover;
    case 11: return qishu;
    case 12: return yun_code;
    case 13: return luck_code;
    case 14: return db_time;
    case 15: return timenum;
    case 16: return status;
    case 17: return ip;
    case 18: return is_show;
    case 19: return is_award;
    case 20: return add_time;
    case 21: return type;
    case 22: return sharecode;
    case 23: return fdis;
    case 24: return agents;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Integer)value$; break;
    case 1: order_id = (java.lang.Integer)value$; break;
    case 2: mid = (java.lang.Integer)value$; break;
    case 3: username = (java.lang.CharSequence)value$; break;
    case 4: buy_id = (java.lang.Integer)value$; break;
    case 5: goods_name = (java.lang.CharSequence)value$; break;
    case 6: goods_price = (java.nio.ByteBuffer)value$; break;
    case 7: price = (java.nio.ByteBuffer)value$; break;
    case 8: qty = (java.lang.Integer)value$; break;
    case 9: total = (java.nio.ByteBuffer)value$; break;
    case 10: cover = (java.lang.Integer)value$; break;
    case 11: qishu = (java.lang.Integer)value$; break;
    case 12: yun_code = (java.lang.CharSequence)value$; break;
    case 13: luck_code = (java.lang.CharSequence)value$; break;
    case 14: db_time = (java.lang.CharSequence)value$; break;
    case 15: timenum = (java.lang.CharSequence)value$; break;
    case 16: status = (java.lang.Integer)value$; break;
    case 17: ip = (java.lang.CharSequence)value$; break;
    case 18: is_show = (java.lang.Integer)value$; break;
    case 19: is_award = (java.lang.Integer)value$; break;
    case 20: add_time = (java.lang.Integer)value$; break;
    case 21: type = (java.lang.Integer)value$; break;
    case 22: sharecode = (java.lang.CharSequence)value$; break;
    case 23: fdis = (java.lang.Integer)value$; break;
    case 24: agents = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   */
  public java.lang.Integer getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Integer value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'order_id' field.
   */
  public java.lang.Integer getOrderId() {
    return order_id;
  }

  /**
   * Sets the value of the 'order_id' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.Integer value) {
    this.order_id = value;
  }

  /**
   * Gets the value of the 'mid' field.
   */
  public java.lang.Integer getMid() {
    return mid;
  }

  /**
   * Sets the value of the 'mid' field.
   * @param value the value to set.
   */
  public void setMid(java.lang.Integer value) {
    this.mid = value;
  }

  /**
   * Gets the value of the 'username' field.
   */
  public java.lang.CharSequence getUsername() {
    return username;
  }

  /**
   * Sets the value of the 'username' field.
   * @param value the value to set.
   */
  public void setUsername(java.lang.CharSequence value) {
    this.username = value;
  }

  /**
   * Gets the value of the 'buy_id' field.
   */
  public java.lang.Integer getBuyId() {
    return buy_id;
  }

  /**
   * Sets the value of the 'buy_id' field.
   * @param value the value to set.
   */
  public void setBuyId(java.lang.Integer value) {
    this.buy_id = value;
  }

  /**
   * Gets the value of the 'goods_name' field.
   */
  public java.lang.CharSequence getGoodsName() {
    return goods_name;
  }

  /**
   * Sets the value of the 'goods_name' field.
   * @param value the value to set.
   */
  public void setGoodsName(java.lang.CharSequence value) {
    this.goods_name = value;
  }

  /**
   * Gets the value of the 'goods_price' field.
   */
  public java.nio.ByteBuffer getGoodsPrice() {
    return goods_price;
  }

  /**
   * Sets the value of the 'goods_price' field.
   * @param value the value to set.
   */
  public void setGoodsPrice(java.nio.ByteBuffer value) {
    this.goods_price = value;
  }

  /**
   * Gets the value of the 'price' field.
   */
  public java.nio.ByteBuffer getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.nio.ByteBuffer value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'qty' field.
   */
  public java.lang.Integer getQty() {
    return qty;
  }

  /**
   * Sets the value of the 'qty' field.
   * @param value the value to set.
   */
  public void setQty(java.lang.Integer value) {
    this.qty = value;
  }

  /**
   * Gets the value of the 'total' field.
   */
  public java.nio.ByteBuffer getTotal() {
    return total;
  }

  /**
   * Sets the value of the 'total' field.
   * @param value the value to set.
   */
  public void setTotal(java.nio.ByteBuffer value) {
    this.total = value;
  }

  /**
   * Gets the value of the 'cover' field.
   */
  public java.lang.Integer getCover() {
    return cover;
  }

  /**
   * Sets the value of the 'cover' field.
   * @param value the value to set.
   */
  public void setCover(java.lang.Integer value) {
    this.cover = value;
  }

  /**
   * Gets the value of the 'qishu' field.
   */
  public java.lang.Integer getQishu() {
    return qishu;
  }

  /**
   * Sets the value of the 'qishu' field.
   * @param value the value to set.
   */
  public void setQishu(java.lang.Integer value) {
    this.qishu = value;
  }

  /**
   * Gets the value of the 'yun_code' field.
   */
  public java.lang.CharSequence getYunCode() {
    return yun_code;
  }

  /**
   * Sets the value of the 'yun_code' field.
   * @param value the value to set.
   */
  public void setYunCode(java.lang.CharSequence value) {
    this.yun_code = value;
  }

  /**
   * Gets the value of the 'luck_code' field.
   */
  public java.lang.CharSequence getLuckCode() {
    return luck_code;
  }

  /**
   * Sets the value of the 'luck_code' field.
   * @param value the value to set.
   */
  public void setLuckCode(java.lang.CharSequence value) {
    this.luck_code = value;
  }

  /**
   * Gets the value of the 'db_time' field.
   */
  public java.lang.CharSequence getDbTime() {
    return db_time;
  }

  /**
   * Sets the value of the 'db_time' field.
   * @param value the value to set.
   */
  public void setDbTime(java.lang.CharSequence value) {
    this.db_time = value;
  }

  /**
   * Gets the value of the 'timenum' field.
   */
  public java.lang.CharSequence getTimenum() {
    return timenum;
  }

  /**
   * Sets the value of the 'timenum' field.
   * @param value the value to set.
   */
  public void setTimenum(java.lang.CharSequence value) {
    this.timenum = value;
  }

  /**
   * Gets the value of the 'status' field.
   */
  public java.lang.Integer getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.Integer value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'ip' field.
   */
  public java.lang.CharSequence getIp() {
    return ip;
  }

  /**
   * Sets the value of the 'ip' field.
   * @param value the value to set.
   */
  public void setIp(java.lang.CharSequence value) {
    this.ip = value;
  }

  /**
   * Gets the value of the 'is_show' field.
   */
  public java.lang.Integer getIsShow() {
    return is_show;
  }

  /**
   * Sets the value of the 'is_show' field.
   * @param value the value to set.
   */
  public void setIsShow(java.lang.Integer value) {
    this.is_show = value;
  }

  /**
   * Gets the value of the 'is_award' field.
   */
  public java.lang.Integer getIsAward() {
    return is_award;
  }

  /**
   * Sets the value of the 'is_award' field.
   * @param value the value to set.
   */
  public void setIsAward(java.lang.Integer value) {
    this.is_award = value;
  }

  /**
   * Gets the value of the 'add_time' field.
   */
  public java.lang.Integer getAddTime() {
    return add_time;
  }

  /**
   * Sets the value of the 'add_time' field.
   * @param value the value to set.
   */
  public void setAddTime(java.lang.Integer value) {
    this.add_time = value;
  }

  /**
   * Gets the value of the 'type' field.
   */
  public java.lang.Integer getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.Integer value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'sharecode' field.
   */
  public java.lang.CharSequence getSharecode() {
    return sharecode;
  }

  /**
   * Sets the value of the 'sharecode' field.
   * @param value the value to set.
   */
  public void setSharecode(java.lang.CharSequence value) {
    this.sharecode = value;
  }

  /**
   * Gets the value of the 'fdis' field.
   */
  public java.lang.Integer getFdis() {
    return fdis;
  }

  /**
   * Sets the value of the 'fdis' field.
   * @param value the value to set.
   */
  public void setFdis(java.lang.Integer value) {
    this.fdis = value;
  }

  /**
   * Gets the value of the 'agents' field.
   */
  public java.lang.CharSequence getAgents() {
    return agents;
  }

  /**
   * Sets the value of the 'agents' field.
   * @param value the value to set.
   */
  public void setAgents(java.lang.CharSequence value) {
    this.agents = value;
  }

  /** Creates a new zz_yundb RecordBuilder */
  public static taotaole.avro.zz_yundb.Builder newBuilder() {
    return new taotaole.avro.zz_yundb.Builder();
  }
  
  /** Creates a new zz_yundb RecordBuilder by copying an existing Builder */
  public static taotaole.avro.zz_yundb.Builder newBuilder(taotaole.avro.zz_yundb.Builder other) {
    return new taotaole.avro.zz_yundb.Builder(other);
  }
  
  /** Creates a new zz_yundb RecordBuilder by copying an existing zz_yundb instance */
  public static taotaole.avro.zz_yundb.Builder newBuilder(taotaole.avro.zz_yundb other) {
    return new taotaole.avro.zz_yundb.Builder(other);
  }
  
  /**
   * RecordBuilder for zz_yundb instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<zz_yundb>
    implements org.apache.avro.data.RecordBuilder<zz_yundb> {

    private int id;
    private int order_id;
    private int mid;
    private java.lang.CharSequence username;
    private int buy_id;
    private java.lang.CharSequence goods_name;
    private java.nio.ByteBuffer goods_price;
    private java.nio.ByteBuffer price;
    private int qty;
    private java.nio.ByteBuffer total;
    private int cover;
    private int qishu;
    private java.lang.CharSequence yun_code;
    private java.lang.CharSequence luck_code;
    private java.lang.CharSequence db_time;
    private java.lang.CharSequence timenum;
    private int status;
    private java.lang.CharSequence ip;
    private int is_show;
    private int is_award;
    private int add_time;
    private int type;
    private java.lang.CharSequence sharecode;
    private int fdis;
    private java.lang.CharSequence agents;

    /** Creates a new Builder */
    private Builder() {
      super(taotaole.avro.zz_yundb.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(taotaole.avro.zz_yundb.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.order_id)) {
        this.order_id = data().deepCopy(fields()[1].schema(), other.order_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.mid)) {
        this.mid = data().deepCopy(fields()[2].schema(), other.mid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.username)) {
        this.username = data().deepCopy(fields()[3].schema(), other.username);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.buy_id)) {
        this.buy_id = data().deepCopy(fields()[4].schema(), other.buy_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.goods_name)) {
        this.goods_name = data().deepCopy(fields()[5].schema(), other.goods_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.goods_price)) {
        this.goods_price = data().deepCopy(fields()[6].schema(), other.goods_price);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.price)) {
        this.price = data().deepCopy(fields()[7].schema(), other.price);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.qty)) {
        this.qty = data().deepCopy(fields()[8].schema(), other.qty);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.total)) {
        this.total = data().deepCopy(fields()[9].schema(), other.total);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.cover)) {
        this.cover = data().deepCopy(fields()[10].schema(), other.cover);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.qishu)) {
        this.qishu = data().deepCopy(fields()[11].schema(), other.qishu);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.yun_code)) {
        this.yun_code = data().deepCopy(fields()[12].schema(), other.yun_code);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.luck_code)) {
        this.luck_code = data().deepCopy(fields()[13].schema(), other.luck_code);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.db_time)) {
        this.db_time = data().deepCopy(fields()[14].schema(), other.db_time);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.timenum)) {
        this.timenum = data().deepCopy(fields()[15].schema(), other.timenum);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.status)) {
        this.status = data().deepCopy(fields()[16].schema(), other.status);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.ip)) {
        this.ip = data().deepCopy(fields()[17].schema(), other.ip);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.is_show)) {
        this.is_show = data().deepCopy(fields()[18].schema(), other.is_show);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.is_award)) {
        this.is_award = data().deepCopy(fields()[19].schema(), other.is_award);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.add_time)) {
        this.add_time = data().deepCopy(fields()[20].schema(), other.add_time);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.type)) {
        this.type = data().deepCopy(fields()[21].schema(), other.type);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.sharecode)) {
        this.sharecode = data().deepCopy(fields()[22].schema(), other.sharecode);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.fdis)) {
        this.fdis = data().deepCopy(fields()[23].schema(), other.fdis);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.agents)) {
        this.agents = data().deepCopy(fields()[24].schema(), other.agents);
        fieldSetFlags()[24] = true;
      }
    }
    
    /** Creates a Builder by copying an existing zz_yundb instance */
    private Builder(taotaole.avro.zz_yundb other) {
            super(taotaole.avro.zz_yundb.SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.order_id)) {
        this.order_id = data().deepCopy(fields()[1].schema(), other.order_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.mid)) {
        this.mid = data().deepCopy(fields()[2].schema(), other.mid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.username)) {
        this.username = data().deepCopy(fields()[3].schema(), other.username);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.buy_id)) {
        this.buy_id = data().deepCopy(fields()[4].schema(), other.buy_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.goods_name)) {
        this.goods_name = data().deepCopy(fields()[5].schema(), other.goods_name);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.goods_price)) {
        this.goods_price = data().deepCopy(fields()[6].schema(), other.goods_price);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.price)) {
        this.price = data().deepCopy(fields()[7].schema(), other.price);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.qty)) {
        this.qty = data().deepCopy(fields()[8].schema(), other.qty);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.total)) {
        this.total = data().deepCopy(fields()[9].schema(), other.total);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.cover)) {
        this.cover = data().deepCopy(fields()[10].schema(), other.cover);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.qishu)) {
        this.qishu = data().deepCopy(fields()[11].schema(), other.qishu);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.yun_code)) {
        this.yun_code = data().deepCopy(fields()[12].schema(), other.yun_code);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.luck_code)) {
        this.luck_code = data().deepCopy(fields()[13].schema(), other.luck_code);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.db_time)) {
        this.db_time = data().deepCopy(fields()[14].schema(), other.db_time);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.timenum)) {
        this.timenum = data().deepCopy(fields()[15].schema(), other.timenum);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.status)) {
        this.status = data().deepCopy(fields()[16].schema(), other.status);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.ip)) {
        this.ip = data().deepCopy(fields()[17].schema(), other.ip);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.is_show)) {
        this.is_show = data().deepCopy(fields()[18].schema(), other.is_show);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.is_award)) {
        this.is_award = data().deepCopy(fields()[19].schema(), other.is_award);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.add_time)) {
        this.add_time = data().deepCopy(fields()[20].schema(), other.add_time);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.type)) {
        this.type = data().deepCopy(fields()[21].schema(), other.type);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.sharecode)) {
        this.sharecode = data().deepCopy(fields()[22].schema(), other.sharecode);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.fdis)) {
        this.fdis = data().deepCopy(fields()[23].schema(), other.fdis);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.agents)) {
        this.agents = data().deepCopy(fields()[24].schema(), other.agents);
        fieldSetFlags()[24] = true;
      }
    }

    /** Gets the value of the 'id' field */
    public java.lang.Integer getId() {
      return id;
    }
    
    /** Sets the value of the 'id' field */
    public taotaole.avro.zz_yundb.Builder setId(int value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'id' field has been set */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'id' field */
    public taotaole.avro.zz_yundb.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'order_id' field */
    public java.lang.Integer getOrderId() {
      return order_id;
    }
    
    /** Sets the value of the 'order_id' field */
    public taotaole.avro.zz_yundb.Builder setOrderId(int value) {
      validate(fields()[1], value);
      this.order_id = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'order_id' field has been set */
    public boolean hasOrderId() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'order_id' field */
    public taotaole.avro.zz_yundb.Builder clearOrderId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'mid' field */
    public java.lang.Integer getMid() {
      return mid;
    }
    
    /** Sets the value of the 'mid' field */
    public taotaole.avro.zz_yundb.Builder setMid(int value) {
      validate(fields()[2], value);
      this.mid = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'mid' field has been set */
    public boolean hasMid() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'mid' field */
    public taotaole.avro.zz_yundb.Builder clearMid() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'username' field */
    public java.lang.CharSequence getUsername() {
      return username;
    }
    
    /** Sets the value of the 'username' field */
    public taotaole.avro.zz_yundb.Builder setUsername(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.username = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'username' field has been set */
    public boolean hasUsername() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'username' field */
    public taotaole.avro.zz_yundb.Builder clearUsername() {
      username = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'buy_id' field */
    public java.lang.Integer getBuyId() {
      return buy_id;
    }
    
    /** Sets the value of the 'buy_id' field */
    public taotaole.avro.zz_yundb.Builder setBuyId(int value) {
      validate(fields()[4], value);
      this.buy_id = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'buy_id' field has been set */
    public boolean hasBuyId() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'buy_id' field */
    public taotaole.avro.zz_yundb.Builder clearBuyId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'goods_name' field */
    public java.lang.CharSequence getGoodsName() {
      return goods_name;
    }
    
    /** Sets the value of the 'goods_name' field */
    public taotaole.avro.zz_yundb.Builder setGoodsName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.goods_name = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'goods_name' field has been set */
    public boolean hasGoodsName() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'goods_name' field */
    public taotaole.avro.zz_yundb.Builder clearGoodsName() {
      goods_name = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'goods_price' field */
    public java.nio.ByteBuffer getGoodsPrice() {
      return goods_price;
    }
    
    /** Sets the value of the 'goods_price' field */
    public taotaole.avro.zz_yundb.Builder setGoodsPrice(java.nio.ByteBuffer value) {
      validate(fields()[6], value);
      this.goods_price = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'goods_price' field has been set */
    public boolean hasGoodsPrice() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'goods_price' field */
    public taotaole.avro.zz_yundb.Builder clearGoodsPrice() {
      goods_price = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'price' field */
    public java.nio.ByteBuffer getPrice() {
      return price;
    }
    
    /** Sets the value of the 'price' field */
    public taotaole.avro.zz_yundb.Builder setPrice(java.nio.ByteBuffer value) {
      validate(fields()[7], value);
      this.price = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'price' field has been set */
    public boolean hasPrice() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'price' field */
    public taotaole.avro.zz_yundb.Builder clearPrice() {
      price = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'qty' field */
    public java.lang.Integer getQty() {
      return qty;
    }
    
    /** Sets the value of the 'qty' field */
    public taotaole.avro.zz_yundb.Builder setQty(int value) {
      validate(fields()[8], value);
      this.qty = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'qty' field has been set */
    public boolean hasQty() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'qty' field */
    public taotaole.avro.zz_yundb.Builder clearQty() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'total' field */
    public java.nio.ByteBuffer getTotal() {
      return total;
    }
    
    /** Sets the value of the 'total' field */
    public taotaole.avro.zz_yundb.Builder setTotal(java.nio.ByteBuffer value) {
      validate(fields()[9], value);
      this.total = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'total' field has been set */
    public boolean hasTotal() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'total' field */
    public taotaole.avro.zz_yundb.Builder clearTotal() {
      total = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'cover' field */
    public java.lang.Integer getCover() {
      return cover;
    }
    
    /** Sets the value of the 'cover' field */
    public taotaole.avro.zz_yundb.Builder setCover(int value) {
      validate(fields()[10], value);
      this.cover = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'cover' field has been set */
    public boolean hasCover() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'cover' field */
    public taotaole.avro.zz_yundb.Builder clearCover() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'qishu' field */
    public java.lang.Integer getQishu() {
      return qishu;
    }
    
    /** Sets the value of the 'qishu' field */
    public taotaole.avro.zz_yundb.Builder setQishu(int value) {
      validate(fields()[11], value);
      this.qishu = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'qishu' field has been set */
    public boolean hasQishu() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'qishu' field */
    public taotaole.avro.zz_yundb.Builder clearQishu() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'yun_code' field */
    public java.lang.CharSequence getYunCode() {
      return yun_code;
    }
    
    /** Sets the value of the 'yun_code' field */
    public taotaole.avro.zz_yundb.Builder setYunCode(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.yun_code = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'yun_code' field has been set */
    public boolean hasYunCode() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'yun_code' field */
    public taotaole.avro.zz_yundb.Builder clearYunCode() {
      yun_code = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'luck_code' field */
    public java.lang.CharSequence getLuckCode() {
      return luck_code;
    }
    
    /** Sets the value of the 'luck_code' field */
    public taotaole.avro.zz_yundb.Builder setLuckCode(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.luck_code = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'luck_code' field has been set */
    public boolean hasLuckCode() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'luck_code' field */
    public taotaole.avro.zz_yundb.Builder clearLuckCode() {
      luck_code = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'db_time' field */
    public java.lang.CharSequence getDbTime() {
      return db_time;
    }
    
    /** Sets the value of the 'db_time' field */
    public taotaole.avro.zz_yundb.Builder setDbTime(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.db_time = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'db_time' field has been set */
    public boolean hasDbTime() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'db_time' field */
    public taotaole.avro.zz_yundb.Builder clearDbTime() {
      db_time = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'timenum' field */
    public java.lang.CharSequence getTimenum() {
      return timenum;
    }
    
    /** Sets the value of the 'timenum' field */
    public taotaole.avro.zz_yundb.Builder setTimenum(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.timenum = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'timenum' field has been set */
    public boolean hasTimenum() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'timenum' field */
    public taotaole.avro.zz_yundb.Builder clearTimenum() {
      timenum = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'status' field */
    public java.lang.Integer getStatus() {
      return status;
    }
    
    /** Sets the value of the 'status' field */
    public taotaole.avro.zz_yundb.Builder setStatus(int value) {
      validate(fields()[16], value);
      this.status = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'status' field has been set */
    public boolean hasStatus() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'status' field */
    public taotaole.avro.zz_yundb.Builder clearStatus() {
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'ip' field */
    public java.lang.CharSequence getIp() {
      return ip;
    }
    
    /** Sets the value of the 'ip' field */
    public taotaole.avro.zz_yundb.Builder setIp(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.ip = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'ip' field has been set */
    public boolean hasIp() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'ip' field */
    public taotaole.avro.zz_yundb.Builder clearIp() {
      ip = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'is_show' field */
    public java.lang.Integer getIsShow() {
      return is_show;
    }
    
    /** Sets the value of the 'is_show' field */
    public taotaole.avro.zz_yundb.Builder setIsShow(int value) {
      validate(fields()[18], value);
      this.is_show = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'is_show' field has been set */
    public boolean hasIsShow() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'is_show' field */
    public taotaole.avro.zz_yundb.Builder clearIsShow() {
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'is_award' field */
    public java.lang.Integer getIsAward() {
      return is_award;
    }
    
    /** Sets the value of the 'is_award' field */
    public taotaole.avro.zz_yundb.Builder setIsAward(int value) {
      validate(fields()[19], value);
      this.is_award = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'is_award' field has been set */
    public boolean hasIsAward() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'is_award' field */
    public taotaole.avro.zz_yundb.Builder clearIsAward() {
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'add_time' field */
    public java.lang.Integer getAddTime() {
      return add_time;
    }
    
    /** Sets the value of the 'add_time' field */
    public taotaole.avro.zz_yundb.Builder setAddTime(int value) {
      validate(fields()[20], value);
      this.add_time = value;
      fieldSetFlags()[20] = true;
      return this; 
    }
    
    /** Checks whether the 'add_time' field has been set */
    public boolean hasAddTime() {
      return fieldSetFlags()[20];
    }
    
    /** Clears the value of the 'add_time' field */
    public taotaole.avro.zz_yundb.Builder clearAddTime() {
      fieldSetFlags()[20] = false;
      return this;
    }

    /** Gets the value of the 'type' field */
    public java.lang.Integer getType() {
      return type;
    }
    
    /** Sets the value of the 'type' field */
    public taotaole.avro.zz_yundb.Builder setType(int value) {
      validate(fields()[21], value);
      this.type = value;
      fieldSetFlags()[21] = true;
      return this; 
    }
    
    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[21];
    }
    
    /** Clears the value of the 'type' field */
    public taotaole.avro.zz_yundb.Builder clearType() {
      fieldSetFlags()[21] = false;
      return this;
    }

    /** Gets the value of the 'sharecode' field */
    public java.lang.CharSequence getSharecode() {
      return sharecode;
    }
    
    /** Sets the value of the 'sharecode' field */
    public taotaole.avro.zz_yundb.Builder setSharecode(java.lang.CharSequence value) {
      validate(fields()[22], value);
      this.sharecode = value;
      fieldSetFlags()[22] = true;
      return this; 
    }
    
    /** Checks whether the 'sharecode' field has been set */
    public boolean hasSharecode() {
      return fieldSetFlags()[22];
    }
    
    /** Clears the value of the 'sharecode' field */
    public taotaole.avro.zz_yundb.Builder clearSharecode() {
      sharecode = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /** Gets the value of the 'fdis' field */
    public java.lang.Integer getFdis() {
      return fdis;
    }
    
    /** Sets the value of the 'fdis' field */
    public taotaole.avro.zz_yundb.Builder setFdis(int value) {
      validate(fields()[23], value);
      this.fdis = value;
      fieldSetFlags()[23] = true;
      return this; 
    }
    
    /** Checks whether the 'fdis' field has been set */
    public boolean hasFdis() {
      return fieldSetFlags()[23];
    }
    
    /** Clears the value of the 'fdis' field */
    public taotaole.avro.zz_yundb.Builder clearFdis() {
      fieldSetFlags()[23] = false;
      return this;
    }

    /** Gets the value of the 'agents' field */
    public java.lang.CharSequence getAgents() {
      return agents;
    }
    
    /** Sets the value of the 'agents' field */
    public taotaole.avro.zz_yundb.Builder setAgents(java.lang.CharSequence value) {
      validate(fields()[24], value);
      this.agents = value;
      fieldSetFlags()[24] = true;
      return this; 
    }
    
    /** Checks whether the 'agents' field has been set */
    public boolean hasAgents() {
      return fieldSetFlags()[24];
    }
    
    /** Clears the value of the 'agents' field */
    public taotaole.avro.zz_yundb.Builder clearAgents() {
      agents = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    @Override
    public zz_yundb build() {
      try {
        zz_yundb record = new zz_yundb();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Integer) defaultValue(fields()[0]);
        record.order_id = fieldSetFlags()[1] ? this.order_id : (java.lang.Integer) defaultValue(fields()[1]);
        record.mid = fieldSetFlags()[2] ? this.mid : (java.lang.Integer) defaultValue(fields()[2]);
        record.username = fieldSetFlags()[3] ? this.username : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.buy_id = fieldSetFlags()[4] ? this.buy_id : (java.lang.Integer) defaultValue(fields()[4]);
        record.goods_name = fieldSetFlags()[5] ? this.goods_name : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.goods_price = fieldSetFlags()[6] ? this.goods_price : (java.nio.ByteBuffer) defaultValue(fields()[6]);
        record.price = fieldSetFlags()[7] ? this.price : (java.nio.ByteBuffer) defaultValue(fields()[7]);
        record.qty = fieldSetFlags()[8] ? this.qty : (java.lang.Integer) defaultValue(fields()[8]);
        record.total = fieldSetFlags()[9] ? this.total : (java.nio.ByteBuffer) defaultValue(fields()[9]);
        record.cover = fieldSetFlags()[10] ? this.cover : (java.lang.Integer) defaultValue(fields()[10]);
        record.qishu = fieldSetFlags()[11] ? this.qishu : (java.lang.Integer) defaultValue(fields()[11]);
        record.yun_code = fieldSetFlags()[12] ? this.yun_code : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.luck_code = fieldSetFlags()[13] ? this.luck_code : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.db_time = fieldSetFlags()[14] ? this.db_time : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.timenum = fieldSetFlags()[15] ? this.timenum : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.status = fieldSetFlags()[16] ? this.status : (java.lang.Integer) defaultValue(fields()[16]);
        record.ip = fieldSetFlags()[17] ? this.ip : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.is_show = fieldSetFlags()[18] ? this.is_show : (java.lang.Integer) defaultValue(fields()[18]);
        record.is_award = fieldSetFlags()[19] ? this.is_award : (java.lang.Integer) defaultValue(fields()[19]);
        record.add_time = fieldSetFlags()[20] ? this.add_time : (java.lang.Integer) defaultValue(fields()[20]);
        record.type = fieldSetFlags()[21] ? this.type : (java.lang.Integer) defaultValue(fields()[21]);
        record.sharecode = fieldSetFlags()[22] ? this.sharecode : (java.lang.CharSequence) defaultValue(fields()[22]);
        record.fdis = fieldSetFlags()[23] ? this.fdis : (java.lang.Integer) defaultValue(fields()[23]);
        record.agents = fieldSetFlags()[24] ? this.agents : (java.lang.CharSequence) defaultValue(fields()[24]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
